services:
  - type: web
    name: our-mart-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0